# when changing this file, need to restart server
# all keys are prefaced with site (e.g. site.title)
title: Dave.Sri Seah Works
description: a collection of applicable experiences
homepage: https://davidseah.com
markdown: kramdown
logo: /assets/img/logo-daveseah-512x400.png
permalink: /blog/:year/:month/:day/:title
github.repository_url: https://github.com/daveseah
github.owner_url: https://davidseah.com
github.zip_url: https://davidseah.com
exclude: ["*.code-workspace", "Gemfile", "*.lock"]
