title: Dave.Sri Seah
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
github.repository_url: https://github.com/daveseah
github.owner_url: https://davidseah.com
github.zip_url: https://davidseah.com
exclude: ['*.code-workspace','Gemfile','*.lock']
